modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="trainresync"
version="1.6.0.b"
displayName="Train Resync"
authors="ashbill"
description='''Fix out-of-sync of Create trains.'''

[[dependencies.trainresync]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.trainresync]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.trainresync]]
modId="create"
mandatory=true
versionRange="[0.5.1.j,)"
ordering="AFTER"
side="BOTH"

[[dependencies.trainresync]]
modId="pantographsandwires"
mandatory=false
versionRange="[0.1.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.trainresync]]
modId="simpleplanes"
mandatory=false
versionRange="[1.20.1-5.3.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.trainresync]]
modId="ctl"
mandatory=false
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
modId="trainresync"
config="trainresync.mixins.json"
