modLoader="javafml"
loaderVersion="[47,)" # Matches Forge 1.20.1+
license="MIT"

[[mods]]
modId="trainresync"
version="1.5.0.c"
displayName="Train Resync"
authors="ashbill"
description='''Fix out-of-sync of Create trains.'''

[[dependencies.trainresync]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.trainresync]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.trainresync]]
modId="create"
mandatory=true
versionRange="[0.5.1.j,)"
ordering="AFTER"
side="BOTH"

[[dependencies.trainresync]]
modId="pantographsandwires"
mandatory=true
versionRange="[0.1.1,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
modId="trainresync"
config="trainresync.mixins.json"
